image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      . /home/gitpod/.sdkman/bin/sdkman-init.sh
      sdk env install
    command: |
      ./gradlew build test

ports:
  - port: 9876
    onOpen: ignore
    visibility: public
