image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      . /home/gitpod/.sdkman/bin/sdkman-init.sh
      sdk env install
    command: |
      gp await-port 6080
      gp await-port 5900
      sleep 100
      time ./gradlew build test

ports:
  - port: 9876
    onOpen: ignore
    visibility: public
  - port: 6080
    onOpen: ignore
    visibility: public
  - port: 5900
    onOpen: ignore
    visibility: public
