apiVersion: apps/v1
kind: Deployment
metadata:
  name: legendary-stats
spec:
  selector:
    matchLabels:
      app: legendary
  replicas: 2
  template:
    metadata:
      labels:
        app: legendary
    spec:
      containers:
      - name: server
        image: ghcr.io/kontaras/legendary-stats:$VERSION_TO_DEPLOY
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: legendary-db
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: legendary-db
              key: db-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: legendary-db
              key: db-pass
---
kind: Service
apiVersion: v1
metadata:
  name: legendary-stats
  labels:
    app: legendary
spec:
  selector:
    app: legendary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
