# Build the server, test, and upload quality metrics to Sonar Cloud and CodeCov.
# Uses Java 11, the current Long Term Supported version of Java.

name: Build, test, and qulity

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is used by Sonar
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache SonarCloud packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Gradle packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build jacocoTestReport  --info
    - name: Sonar
      if: ${{ github.actor != 'dependabot[bot]' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonarqube --info
    - name: CodeCov
      uses: codecov/codecov-action@v2.0.2
      with:
        verbose: true
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/test-publish' }}
    #needs: build
    steps:
      - run: echo ${{github.event_name}} ${{github.ref}}
  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - run: echo ${{github.event_name}} ${{github.ref}}
  
